16.0 mig endpoint route handler
OCA/web-api pull request #12
Opened 2022-10-11 09:26 UTC by lmignon

[ ] Fix tests: Unfortunately from 16.0 it's no more allowed to call `new` on an abstract model...

2022-10-17 09:27 UTC, simahawk commented
FTR we discussed the evolution of this tool during OCA days and I have to draft something based on a combo of #13 + #3

2023-01-19 11:29 UTC, rousseldenis requested changes
Code review

2023-01-19 11:29 UTC, rousseldenis commented on endpoint_route_handler/models/endpoint_route_handler.py
> +            if model != self._name and self.env[model].sudo().search_count(
Could you do the search before the loop with a read_group?

2023-01-19 11:29 UTC, rousseldenis commented on endpoint_route_handler/models/endpoint_route_handler.py
> +            raise exceptions.UserError(
In constraints, you should ValidationError instead

2023-01-19 11:29 UTC, rousseldenis commented on endpoint_route_handler/models/endpoint_route_handler.py
> +                raise exceptions.UserError(
Same as above

2023-02-17 09:49 UTC, simahawk commented
I've re-done the migration here and w/ a workaround that makes it work `.new` on v15 and v16 https://github.com/OCA/web-api/pull/17

2023-02-27 13:54 UTC, lmignon commented
superseded by #17

2023-02-27 13:54 UTC, closed without merging