[16.0][MIG] webservice: Migration to 16.0
OCA/web-api pull request #23
Opened 2023-07-10 09:22 UTC by EvaSForgeFlow

Passes the tests

2023-07-10 13:06 UTC, OriolMForgeFlow approved these changes

2023-07-10 13:06 UTC, OriolMForgeFlow approved these changes
LGTM!

2023-07-20 10:53 UTC, LoisRForgeFlow commented on webservice/components/request_adapter.py
> +            method, self.collection.url.format(**kwargs), **new_kwargs, timeout=None
Include timeout in the new_kwargs update a couple of lines above, otherwise this will fail is timeout key is specified in when caling _request method

2023-07-20 11:23 UTC, simahawk requested changes
please fwd port changes from v14 too

2023-07-24 08:07 UTC, OriolMForgeFlow commented
Hi @simahawk , 
The FW Ports of #7 and #8 have been added.

2023-07-25 17:24 UTC, simahawk approved these changes
LG. Thanks for your work :pray: 
Question: out of curiosity, for which purpose do you need this on v16? EDI or another use case?

2023-07-25 17:25 UTC, simahawk commented
/ocabot migration endpoint
/ocabot merge nobump

2023-07-25 17:26 UTC, simahawk commented
Typo-ed module name before...

/ocabot migration webservice

2023-07-25 17:29 UTC, merged

2023-07-26 06:27 UTC, OriolMForgeFlow commented
> LG. Thanks for your work 🙏 Question: out of curiosity, for which purpose do you need this on v16? EDI or another use case?

Yes, we would like to use EDI in v16. We are also in the process of migrating it.