[14.0][FIX] endpoint_route_handler: Use dedicated cursor for registry
OCA/web-api pull request #37
Opened 2024-03-04 17:29 UTC by grindtildeath

When the request cursor is used to instantiate the EndpointRegistry in the call to routing_map, the READ REPEATABLE isolation level will ensure that any value read from the DB afterwards, will be the same than when the first SELECT is executed.

This is breaking the oauth flow as the oauth token that is written at the beggining of the oauth process cannot be read by the cursor computing the session token, which will read an old value. Therefore when the session security check is performed, the session token is outdated as the new session token is computed using an up to date cursor.

By using a dedicated cursor to instantiate the EndpointRegistry, we ensure no read is performed on the database using the request cursor which will in turn use the updated value of the oauth token to compute the session token, and the security check will not fail.

2024-03-05 07:53 UTC, simahawk requested changes
Thanks for tracking down this issue :)

2024-03-05 07:53 UTC, simahawk commented on endpoint_route_handler/models/ir_http.py
> +                )
This will cause too much noise. Use `warning` if you want to keep it.
```suggestion
```

2024-03-05 07:53 UTC, simahawk commented on endpoint_route_handler/models/ir_http.py
> +        e_registry = cls._endpoint_route_registry(http.request.env.cr)
shouldn't we use a new cr here too?

2024-03-05 07:54 UTC, simahawk commented
One last bit: can you add the explanation as a comment?

2024-03-05 10:25 UTC, simahawk commented
I'll apply the changes

2024-03-05 14:51 UTC, grindtildeath commented on endpoint_route_handler/models/ir_http.py
> +        e_registry = cls._endpoint_route_registry(http.request.env.cr)
It doesn't seem to be required for Oauth flow, so I don't know :shrug:

2024-07-04 07:11 UTC, simahawk approved these changes
Live on prod since 4 months.

2024-07-04 07:11 UTC, simahawk commented
/ocabot merge patch

2024-07-04 07:13 UTC, merged