[18.0][MIG] endpoint
OCA/web-api pull request #78
Opened 2024-12-17 11:49 UTC by JordiMForgeFlow

2024-12-20 21:20 UTC, dreispt approved these changes

2025-01-30 15:26 UTC, JordiMForgeFlow commented
@simahawk @lmignon ready for review :)

2025-01-31 00:45 UTC, dnplkndll requested changes

2025-01-31 00:45 UTC, dnplkndll commented on endpoint/views/endpoint_view.xml
> +        <field name="view_mode">tree,form</field>
```suggestion
        <field name="view_mode">list,form</field>
```

2025-01-31 00:45 UTC, dnplkndll commented on endpoint/views/endpoint_view.xml
> +        <field name="view_mode">tree,form</field>
error on menu item

2025-01-31 07:27 UTC, JordiMForgeFlow commented on endpoint/views/endpoint_view.xml
> +        <field name="view_mode">tree,form</field>
fixed, thank you! :)

2025-01-31 09:47 UTC, simahawk requested changes

2025-01-31 09:47 UTC, simahawk commented on endpoint/views/endpoint_view.xml
> +    <record model="ir.ui.view" id="endpoint_endpoint_search_view">
Recently I've added mixin views for search and list on v14. Could you please fwd port them? :pray: 

https://github.com/OCA/web-api/pull/87/commits/687032089b61d97d093af0d6ef0377a477d4f2c5

2025-01-31 09:47 UTC, simahawk commented on endpoint/data/server_action.xml
> +records.filtered(lambda x: not x.registry_sync).write({"registry_sync": True})
We should remove the `filtered` call. There's a similar fix for this done in shopfloor_base recently.
Please, do it in a separated commit that we can backport ;)

2025-01-31 10:00 UTC, JordiMForgeFlow commented
@simahawk should be now ready :)

2025-01-31 10:59 UTC, simahawk approved these changes

2025-01-31 11:00 UTC, simahawk commented
/ocabot migration endpoint
/ocabot merge nobump

Muchas gracias! :)

2025-01-31 11:08 UTC, merged