[IMP] endpoint: support usage of querystring parameters
OCA/web-api pull request #80
Opened 2024-12-23 11:48 UTC by dreispt

2024-12-27 13:17 UTC, dreispt commented
Review is appreciated but please don't merge yet, there might be a few changes.

2025-01-03 10:19 UTC, dreispt commented
Ready for review.

2025-01-31 11:29 UTC, simahawk requested changes
Thank you! Something I was thinking about since a while ;)

Just 1 remark about the naming: I prefer to make explicit everywhere down the stack, as `params` is quite an abused term :wink:

2025-01-31 11:29 UTC, simahawk commented on endpoint/models/endpoint_mixin.py
> +        * params
```suggestion
        * querystring_params
```

2025-01-31 11:29 UTC, simahawk commented on endpoint/models/endpoint_mixin.py
> +    def _handle_exec__code(self, request, params=None):
```suggestion
    def _handle_exec__code(self, request, querystring_params=None):
```

2025-01-31 11:29 UTC, simahawk commented on endpoint/controllers/main.py
> +        result = endpoint._handle_request(request, params=params)
```suggestion
        result = endpoint._handle_request(request, querystring_params=params)
```

2025-01-31 11:29 UTC, simahawk commented on endpoint/models/endpoint_mixin.py
> +        eval_ctx["params"] = params or {}
```suggestion
        eval_ctx["querystring_params"] = querystring_params or {}
```

2025-01-31 11:29 UTC, simahawk commented on endpoint/models/endpoint_mixin.py
> +    def _handle_request(self, request, params=None):
```suggestion
    def _handle_request(self, request, querystring_params=None):
```

2025-01-31 11:29 UTC, simahawk commented on endpoint/models/endpoint_mixin.py
> +            # In case the handler does not support params
I doubt we have any other handler ATM but just in case... ok, let's keep this but I would add a separated commit for backward compat that we can easily drop on migration. 
Something like:

```
[imp] endpoint: support querystring params
[imp] endpoint: backward compat for querystring params

Old handlers might not accept this new kw args
Trash this commit in future versions. Eg: v18.
```

2025-01-31 11:29 UTC, simahawk commented on endpoint/models/endpoint_mixin.py
> +                res = handler(request, params=params)
```suggestion
            if querystring_params:
                res = handler(request, querystring_params=querystring_params)
```

2025-12-28 12:55 UTC, closed without merging